### ISSUE TITLE
Feature request: tag file support for cross linking

### ISSUE THREAD

**Issue by LB--** [CodeDocs/CodeDocs#1]
From https://github.com/mosra/magnum/issues/113#issuecomment-199220264

> tag files to crosslink Corrade and Magnum documentation (crucial, I think)

[Corrade](https://github.com/mosra/corrade) and [Magnum](https://github.com/mosra/magnum) are two separate GitHub repositories but their documentation refers to each other's documentation. For example:
[`@ref building-corrade "Corrade"`](https://github.com/mosra/magnum/blob/1f0617ac2798ba995fdd0d176cf1c3f6a1e3106b/doc/getting-started.dox#L64) linkes to the Corrade documentation, as allowed [here in the Doxyfile](https://github.com/mosra/magnum/blob/1f0617ac2798ba995fdd0d176cf1c3f6a1e3106b/Doxyfile#L2068)

[Relevant Doxygen documentation](https://www.stack.nl/~dimitri/doxygen/manual/external.html)

**Comment by paulnovo** [comment]
@LB-- Others have asked for this, and I am beginning to think this may be easier than I originally thought, and actually very powerful. I think I might turn on tagfiles for all repositories on codedocs. Then have a TAGFILES like option in the .codedocs file where you just put the repo name. You could even do other repositories that aren't yours. ie:

```
TAGFILES = mosra/corrade boostorg/regex 
```

Does this sound good?

**Comment by mosra** [comment]
That sounds great.

**Comment by paulnovo** [comment]
Great, I'll get to it!

**Comment by paulnovo** [comment]
@mosra I think I have it working, I forked magnum [here](https://github.com/CodeDocs/magnum) which uses the TAGLINKS option I added to the .codedocs file. This refers to the tags in my fork of [corrade](https://github.com/CodeDocs/corrade). You can see the resulting docs [here](https://codedocs.xyz/CodeDocs/magnum/).

Would you mind taking a look? It seems to be working from what I can tell.

**Comment by mosra** [comment]
Wow, yes, it works flawlessly. Great! :)

**Comment by paulnovo** [comment]
Thanks for testing this, I'll mark it as closed.
