### ISSUE TITLE
Facilitate locally running doxygen when using codedocs

### ISSUE THREAD

**Issue by jbeder** [CodeDocs/CodeDocs#13]
It would be nice to have a simple way to locally produce the same docs that codedocs produces.

**Comment by MarkCallow** [comment]
There is. Create your own Doxygen configuration file and in your .codedocs file put

```
DOXYFILE = mydoxyfile
```

To build docs locally you then run

```
doxygen mydoxyfile
```

CodeDocs will ignore the `OUTPUT_DIRECTORY` setting in `mydoxyfile` that specified where locally to drop the output.

**Comment by paulnovo** [comment]
@jbeder With the recent update to CodeDocs, pretty much all the Doxygen options related to html output are enabled. So if you follow msc-'s suggestion, the output should be identical when run locally.

I am going to close this issue, if this doesn't work, please re-open it.
