### ISSUE TITLE
Allow use of custom stylesheets / headers / footers

### ISSUE THREAD

**Issue by ben-marshall** [CodeDocs/CodeDocs#15]
I have spent a while tweaking doxygen's output to make it a little clearer to read, and this relies on using custom header.html, footer.hml and style.css files.

CodeDocs (which is awesome) doesn't currently take any notice of these (which is sad!).

Could this be implemented?

Thanks :)

**Comment by paulnovo** [comment]
@ben-marshall I am currently testing a solution to turn on most of the doxygen settings, including custom header, footer and stylesheets. Stay tuned.

**Comment by paulnovo** [comment]
@ben-marshall This should currently work. If you still have issues, please reopen this issue.
