### ISSUE TITLE
Multiple "README.md" files not resolved on codedocs

### ISSUE THREAD

**Issue by dabercro** [CodeDocs/CodeDocs#16]
If I have multiple README.md files that I link to from the root repository, codedocs.xyz is not able to resolve the different files.

Specifically, I have the links:

```
[Running Tests](test/README.md) <br>
[Analysis Workspace](templates/README.md) <br>
[Command Line Tools Reference](bin/README.md) <br>
```

on my root README. Only the first link renders on codedocs.xyz. I would rather not change the names so that READMEs can be seen when navigating GitHub too.

Running doxygen on this locally works fine for me.

**Comment by paulnovo** [comment]
I am in the middle of testing changes to CodeDocs that should make things render more closely to running doxygen locally, if not identical. What repository are you having the issue with? I'll check to see if this issue is resolved with the new changes.

**Comment by dabercro** [comment]
I'm using CodeDocs for this repository: 
https://github.com/dabercro/CrombieTools

The build log is then here:
https://codedocs.xyz/dabercro/CrombieTools.log

It's just some code for grad school, so no rush. Just thought you'd like to know! Thanks.

**Comment by paulnovo** [comment]
@dabercro Is this working correctly now?

**Comment by dabercro** [comment]
Yep, that works great, thanks!
