### ISSUE TITLE
Push doesn't seem to cause docs to rebuild

### ISSUE THREAD

**Issue by HipsterSloth** [CodeDocs/CodeDocs#18]
First off, thanks a bunch for providing this service! It's nice to not have to do any github-pages setup to display doc builds. As for my issue: 

I'm one of the maintainers for PSMoveService
https://github.com/cboulay/PSMoveService

I recently added codedocs to our project:
https://codedocs.xyz/HipsterSloth/PSMoveService/

It generated documentation just fine for the initial build, but it doesn't seem to want to update the docs on subsequent pushes to the repo. 

I'm wondering if me being a maintainer not the owner of the repo has something to do with it?

Attached is my codedocs config (renamed from .codedocs to codedocs.txt) if that is any help.
[codedocs.txt](https://github.com/CodeDocs/CodeDocs/files/901310/codedocs.txt)

Hopefully this is just a case of me be dumb and not understanding some setup detail.

Thanks!

**Comment by paulnovo** [comment]
@HipsterSloth It looks like you enabled HipsterSloth/PSMoveService, which is a fork of the repo you have been pushing updates to cboulay/PSMoveService. If you have access to the cboulay version, you should see it under the accounts drop down on the upper right of codedocs. Switch to that account, and enable PSMoveService there. Hope this helps.

**Comment by HipsterSloth** [comment]
Aha! That makes sense. I forgot that I had made a clone of the PSMoveService repo and then incorrectly assumed that the repo list was an aggregate of all repos I had access to. Looks like everything is working as it should. Thanks for the help!
