### ISSUE TITLE
CodeDocs does not use most of the doxygen settings!

### ISSUE THREAD

**Issue by MartijnKaijser** [CodeDocs/CodeDocs#5]
Current Kodi master comes out like this
https://codedocs.xyz/xbmc/xbmc/pages.html
with this https://github.com/xbmc/xbmc/pull/9674 it ends up like
https://codedocs.xyz/MartijnKaijser/xbmc/pages.html

Also see the following github comment:
https://github.com/xbmc/xbmc/pull/9652#issuecomment-213773804

**Comment by paulnovo** [comment]
@MartijnKaijser Yes, currently only a subset of the doxygen settings are enabled. New settings are added when requested so we can make sure they work correctly. Which doxygen settings would you like enabled?

**Comment by MartijnKaijser** [comment]
@AlwinEsch you know which ones?

**Comment by paulnovo** [comment]
@MartijnKaijser @AlwinEsch I took a look at the difference between the default configuration and your configuration, and these are the non-default options you use:

```
PROJECT_NUMBER
PROJECT_BRIEF
PROJECT_LOGO
ABBREVIATE_BRIEF
ALWAYS_DETAILED_SEC
SHORT_NAMES
DISTRIBUTE_GROUP_DOC
TYPEDEF_HIDES_STRUCT
EXTRACT_LOCAL_CLASSES
HIDE_SCOPE_NAMES 
SHOW_INCLUDE_FILES
SORT_MEMBER_DOCS
SORT_BRIEF_DOCS
SORT_BY_SCOPE_NAME
STRICT_PROTO_MATCHING
SHOW_FILES
SHOW_NAMESPACES
LAYOUT_FILE
IMAGE_PATH
HTML_EXTRA_FILES 
HTML_TIMESTAMP
DISABLE_INDEX
GENERATE_TREEVIEW
CLASS_DIAGRAMS
```

Alot of the yes/no options can be added quickly, plus PROJECT_NUMBER, PROJECT_BRIEF, and PROJECT_LOGO. I'll keep you updated as they are added. Let me know if any options are more important than others.

**Comment by mosra** [comment]
@paulnovo I think this is really just needless duplication, wouldn't it make more sense to just focus on #3?

**Comment by MartijnKaijser** [comment]
Good idea i think.

**Comment by AlwinEsch** [comment]
Has looked over my Doxyfile from addon-dev-kit, it has the following differences to default:

```
PROJECT_NAME
PROJECT_NUMBER
PROJECT_BRIEF
PROJECT_LOGO
OUTPUT_DIRECTORY  # I know not needed for CodeCods :)
ALWAYS_DETAILED_SEC
STRIP_FROM_INC_PATH
SHORT_NAMES
ALIASES
DISTRIBUTE_GROUP_DOC
INLINE_GROUPED_CLASSES
TYPEDEF_HIDES_STRUCT
EXTRACT_LOCAL_CLASSES
HIDE_SCOPE_NAMES
HIDE_COMPOUND_REFERENCE
SORT_MEMBER_DOCS
SORT_BRIEF_DOCS
SORT_BY_SCOPE_NAME
STRICT_PROTO_MATCHING
SHOW_FILES
SHOW_NAMESPACES
LAYOUT_FILE
INPUT
FILE_PATTERNS
RECURSIVE
EXAMPLE_PATH
EXAMPLE_PATTERNS
IMAGE_PATH
HTML_EXTRA_FILES
DISABLE_INDEX
GENERATE_TREEVIEW
GENERATE_LATEX
PREDEFINED
CLASS_DIAGRAMS
HAVE_DOT
```

Few of them are not needed for your project.

About the issue #3 is also good idea for me.

**Comment by paulnovo** [comment]
@MartijnKaijser @AlwinEsch I added support for most of those settings you requested. You can see the results on my [Kodi fork](https://codedocs.xyz/CodeDocs/xbmc/).

The ones remaining are: PROJECT_LOGO, LAYOUT_FILE, IMAGE_PATH, HTML_EXTRA_FILES, STRIP_FROM_INC_PATH,, and PREDEFINED. I'll add these shortly.

**Comment by MartijnKaijser** [comment]
Great. Thx

**Comment by MartijnKaijser** [comment]
@AlwinEsch i've updated our CodeDocs file however the Python Docs are not correctly generated.\
https://codedocs.xyz/xbmc/xbmc/group__python.html
Some setting missing?

**Comment by paulnovo** [comment]
@MartijnKaijser I took a look at this, is the problem the "**"s showing up before the module descriptions, and the descriptions are not bold? I was unable to figure out what this is related to, any pointers?

I did notice that inside a couple of modules (ie https://codedocs.xyz/xbmc/xbmc/group__python__xbmcgui.html), there appears to be a lot missing, and I think this is related to EXTRACT_ALL being unsupported. I'll add that asap. BTW, there has been a bit of radio silence on my part, as I am trying to rework things so all options are available. Stay tuned.

**Comment by MartijnKaijser** [comment]
@paulnovo the python part should look like actual PyDocs and it shouldn't show the C++ classes

**Comment by MartijnKaijser** [comment]
Here's an example of expected output
http://alwinesch.github.io/group__python__xbmcgui.html
http://alwinesch.github.io/group__python__xbmcplugin.html

**Comment by MartijnKaijser** [comment]
Just small nudge to see how to proceed as kodi v17 is nearing beta and I'd like to have the doxygen for our python modules available. 
@AlwinEsch how can we get this done?

**Comment by paulnovo** [comment]
@MartijnKaijser and @AlwinEsch I just added the remaining doxygen settings, actually, pretty much all the settings the affect html output. How does this look?

https://codedocs.xyz/CodeDocs/xbmc/group__python__xbmcgui.html
https://codedocs.xyz/CodeDocs/xbmc/group__python__xbmcplugin.html

**Comment by paulnovo** [comment]
I am going to close this issue as all the requested Doxygen options are available now. Please reopen the issue if something is not working.

**Comment by MartijnKaijser** [comment]
Looks good. Thx
