### ISSUE TITLE
EXCLUDES & EXCLUDE_PATTERNS not fully excluding files

### ISSUE THREAD

**Issue by MarkCallow** [CodeDocs/CodeDocs#6]
Links to excluded files and "classes" still appear in the ToC and the excluded files are scanned.

With the project at https://github.com/msc-/KTX I get the documentation build seen at https://codedocs.xyz/msc-/KTX/. Although its [.codedocs](https://github.com/msc-/KTX/blob/master/.codedocs) excludes a number of files and directories, artefacts from them can be seen in the generated documentation. Here is the generated tree view:

![screen shot 2016-05-11 at 2 48 25 pm](https://cloud.githubusercontent.com/assets/2244683/15171200/68ac2756-1787-11e6-9578-443bfc49d182.png)

The text "About the GLEW debug libraries" comes from the file other_lib/win/README.md which is in an excluded directory (other_lib) so the file has definitely been scanned and affected the ToC. However the EXCLUDE has been partially honored, clicking on this link gets a file not found error.

All the directories listed under File List except for `include` and `lib` are in the EXCLUDES list yet here they are in the ToC. Clicking these also gets a file not found error. Clicking Classes->Class List reveals a long list of "classes" most of which, e.g. `SDL_*` are only referenced from files in excluded directories so shouldn't be here. Clicking these also get file not found.

**Comment by paulnovo** [comment]
Oops, I left a comment in #3, but basically I think EXCLUDES are working, and it might be a browser caching issue. Could you try refreshing the page to verify? Because I get this:

![snapshot8](https://cloud.githubusercontent.com/assets/1461767/15183857/eaa5509c-1760-11e6-8b24-945e8fe650e8.png)

**Comment by MarkCallow** [comment]
Yes they do seem to be working. Please close this unless you want to keep it open to track the caching issue.

**Comment by paulnovo** [comment]
Ok, I created #11 to track the caching issue, and am closing this.
