### ISSUE TITLE
Documentation needed

### ISSUE THREAD

**Issue by MarkCallow** [CodeDocs/CodeDocs#8]
Some minimal documentation is needed to explain what CodeDocs does and in particular what happens when you "Git push to update the documentation". For example, does that push to the repo's gh_pages branch? Does it create that branch if one doesn't exist?

**Comment by LB--** [comment]
> does that push to the repo's gh_pages branch? Does it create that branch if one doesn't exist?

Neither - last I checked the documentation was hosted courtesy of CodeDocs.

**Comment by paulnovo** [comment]
Yes, the basic function is to notice updates to the repository (git push's to GitHub), rerun doxygen, and then host the new html documentation. The html documentation is hosted at https://CodeDocs.xyz/[User/Organization]/[RepositoryName]/

**Comment by MarkCallow** [comment]
Ah! I misunderstood, which only goes to show that a little more documentation would be useful.

@LB where did you check? Or are you just being facetious?

**Comment by LB--** [comment]
@msc-

> where did you check? Or are you just being facetious?

I meant that _your_ documentation would be hosted by CodeDocs. As for CodeDocs' own documentation, we could use the wiki on this repository if @paulnovo creates it.

**Comment by paulnovo** [comment]
@LB-- I just created a wiki, and anyone _should_ be able to edit it.

**Comment by LB--** [comment]
@paulnovo I went through the PRs and added a list of the currently supported options (to my knowledge) to the wiki - could you double check?

**Comment by paulnovo** [comment]
@LB-- This is fantastic, thank you. I'll double check and see if anything is missing. Also, I'll add a link to the wiki from the codedocs website. Thanks again!

**Comment by MarkCallow** [comment]
@LB-- thanks for making that list. I don't think INPUT is supported though. It wasn't working a few days ago. I had to add EXCLUDES in my .codedocs file because the INPUT in my linked doxygen config was being ignored. @paulnovo?

**Comment by paulnovo** [comment]
@msc- Yes, INPUT is not supported. I just updated the wiki.  Incidentally, I'll probably lift this restriction (and many others) shortly.

**Comment by paulnovo** [comment]
I will close this issue with the addition of the wiki.
