### ISSUE TITLE
More config options

### ISSUE THREAD

**Issue by MarkCallow** [CodeDocs/CodeDocs#9]
I have the following non default options in my project:

OPTIMIZE_OUTPUT_FOR_C
EXTRACT_LOCAL_CLASSES
HIDE_UNDOC_MEMBERS
HIDE_UNDOC_CLASSES
CASE_SENSE_NAMES
VERBATIM_HEADERS
ALPHABETICAL_INDEX
QHP_NAMESPACE
DISABLE_INDEX
GENERATE_TREEVIEW

GENERATE_TREEVIEW & DISABLE_INDEX are working in a config file linked from my .codedocs.

PAPER_TYPE also differs but that is probably only relevant when generating pdf. GENERATE_MAN and MAN_LINKS differ but are only needed when generating man format. Do you have any plan to support man format docs?

I also need INPUT_ENCODIING as I sometime have to deal with files in shiftjis/cp932 encoding.

I will need INTERNAL_DOCS in the near future once I have figured out how to style internal items differently.

**Comment by paulnovo** [comment]
@msc- EXTRACT_LOCAL_CLASSES, HIDE_UNDOC_MEMBERS, HIDE_UNDOC_CLASSES, DISABLE_INDEX, and GENERATE_TREEVIEW should already work. I'll look into the rest.

I don't have plans to support man files. How would you like this to work? Host the man files on the codedocs website for download?

**Comment by paulnovo** [comment]
Also, is QHP_NAMESPACE used for html generation? It sounds like it is used for a "Qt Help Project", which I must admit, I don't know much about.

**Comment by MarkCallow** [comment]
I need to think more about the man pages. My plan is to include them in installers with the code they are documenting, so generating them myself as part of the build is probably the way to go.

QHP_NAMESPACE is not used for html per se. Here is the comment from config

```
# If the GENERATE_QHP tag is set to YES and both QHP_NAMESPACE and
# QHP_VIRTUAL_FOLDER are set, an additional index file will be generated that
# can be used as input for Qt's qhelpgenerator to generate a Qt Compressed Help
# (.qch) of the generated HTML documentation.
# The default value is: NO.
# This tag requires that the tag GENERATE_HTML is set to YES.
```

So I don't think it is useful for CodeDocs to support this. I think I only changed it because the default is org.doxygen.Project. I am not using Qt.

**Comment by MarkCallow** [comment]
Please enable OPTIMIZE_OUTPUT_FOR_C as soon as possible. I just verified that setting this to YES is what replaces 'Classes' with 'Data Structures' in the tree view. With this enabled I'll be able to use CodeDocs for my project.

**Comment by paulnovo** [comment]
@msc-  have added all of your requested options except QHP_NAMESPACE, PAPER_TYPE, GENERATE_MAN and MAN_LINKS, since they don't seem relevant for html generation. But the others should work. Feel free to re-open this issue if you have trouble with the new options.
